### ISSUE TITLE
Know if I need to update ATutor version .2 to .3-b1

### ISSUE THREAD

**Issue by es24tv** [atutor/ATutor#140] opened 2017-12-30 12:19 UTC
Dear Greg,

I am using version 2.2.2 from the date of its release. There are some details that have been left poendientes to solve for "future updates". Please, I need to know if it's worth it in my case install the new version 2.2.3-b1

I consult if these problems that I have in my installation (2.2.2) are solved in the new update 2.2.3-b1:

1) Subject treated at http://www.atutor.ca/view/7/26216/1.html on 2017-03-29

Is it resolved in 2.2.3-1b as it says http://www.atutor.ca/atutor/mantis/view.php?id=5779? In "VIEW STATUS" it continues to appear as "OPEN"

2) Subject treated on 2017-02-27 at http://www.atutor.ca/view/7/26178/1.html

The "patch 10" has not solved the problem of the quotes.

Is it solved, according to what you see in www.atutor.ca/atutor/mantis/view.php?id=5762? Keep figuring as

I, at least, do not find other problems in version 2.2.2 but they are important for me because these are issues that are used a lot in my courses and I usually have students confused with these problems.

3) Can I install the Spanish language pack "atutor_2_2_2_es-es.zip" that I have exported from my current installation to my PC? During the last months I was making several adjustments with the editor of the language that I would like to avoid having to do again in the new installation.

3) Will the version of ATutor 2.2.3-b1 work well, although the version of PHP that I am using in my vps is 5.3.3?

I wish you a very happy year 2018!

Best Regards,

Mario

**Comment by atutorlangs** [comment] 2017-12-30 14:54
ATutor 2.2.3 is primarily an update to work with PHP7, and to connect to atutor.github.io for languages and updates etc., as atutor.ca will be shut down soon. ATutor 2.2.3 will still work with older versions of PHP, like 5.3.3, but won't have other fixes or feature changes.

My focus now is on getting 2.2.3 stable, so it will function well into the future as I retire from ATutor in July. I will not be making any significant changes otherwise. The hope is moving ATutor away from atutor.ca to github will attract more developer level users who are able to make adjustments to ATutor and support others. It will be up to the community to support itself through atutor.github.io and through the github repositories. 

My suggestion for you is to find a partner or hire a person with some PHP/developer background to assist with these types of issues. The free help I have been providing for nearly 15 years will no longer be available.

**Comment by es24tv** [comment] 2017-12-30 17:06
I trust that the evolution of ATutor also means good progress in your professional career and attractive personal challenges.

I think you know that I am an ATutor urinator since 2002. I think with version 1.3. I will see, in the future, how I can make the new ATutor style compatible with my business model.

For now, please, I beg you if you can confirm that these two problems that exist in version 2.2.2 are solved (quotes in the emails that the forums send and that the reading list links open in new sales). The rest of version 2.2.2 does not present problems.

Now, I'm doing a new installation of version 2.2.3-b1 (in a new directory, with the usual procedure) but now I find that when trying to log in as an administrator the error appears: "ATutor was unable to access the database. the problem persists, please report this to an Administrator with this date reference (12/30/2017 05:59:41 pm) That account has been disabled. "

The whole process of the installation is normal, there are no errors during the installation. I have created the table previously as administrator of the vps (with plesk), verified the status and permissions of all the files ... the usual. But I have this error.

I appreciate if you can suggest the cause of the problem.

Thank you

Mario

**Comment by atutor** [comment] 2017-12-30 19:50
Your issues are in the bug tracker, but I cannot guarantee they will be fixed for the next release. You might find yourself a freelance PHP programmer to help you. Someone who knows how to use github, so the fixes can be contributed to upcoming 2.2.3 final release.

Regarding 2.2.3-b1 installation and login as admin, I am not able to reproduce the problem myself. The version you have (2.2.3-b1) is the first beta. The most recent code can be downloaded from github:
https://github.com/atutor/ATutor/archive/master.zip

**Comment by atutor** [comment] 2018-02-22 23:37
I'm looking into the issues you mentioned now, and have a question.
Have you installed patch 12?

**Comment by atutor** [comment] 2018-02-23 00:06
Here's the fix for the forum quotes problem:
https://github.com/atutor/ATutor/commit/cce297e070be5d9edbad29232ebbff7d56411079#diff-9348e5b6c2c610068ba8c564e9c81d9b

**Comment by es24tv** [comment] 2018-02-23 02:24
Yes, it installed.

 

De: ATutor [mailto:notifications@github.com] 
Enviado el: viernes, 23 de febrero de 2018 0:37
Para: atutor/ATutor <ATutor@noreply.github.com>
CC: es24tv <aula@miclase.es>; Author <author@noreply.github.com>
Asunto: Re: [atutor/ATutor] Know if I need to update ATutor version .2 to .3-b1 (#140)

 

I'm looking into the issues you mentioned now, and have a question.
Have you installed patch 12?

**Comment by gregrgay** [comment] 2018-02-23 14:06
Patch 12 should have fixed the problem. 
Double check the lines in the diff linked in my previous message, with the lines in the code of your installation, which adds the htmlspecialchars_decode function to turn the entities back into quotes. 

If not as shown in the diff, manually update the line  using a text editor.

**Comment by gregrgay** [comment] 2018-02-23 14:09
Regarding the reading list problem, I did find an issue, which causes the ATutor session to end shortly after viewing a resource, logging the user out. I'm not sure if that's what you are trying to describe.

If not, can you try to describe the problem again.

**Closed** 2018-06-21 22:21 UTC
